name: Print Environment Variables

on:
  push:
    branches:
      - main

jobs:
  print-env-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Print Environment Variables
        run: |
          env
